<?php
// expat-guide.php - Comprehensive Qatar Expatriate Guide
require_once __DIR__ . '/includes/db.php';
require_once __DIR__ . '/includes/widgets.php';

$settings = get_settings();
$pageTitle = t('Qatar Expat Survival & Living Guide', 'ഖത്തർ പ്രവാസി സമഗ്ര ഗൈഡ്');
$pageDesc = t('Essential guide for Qatar expatriates covering Metrash2, QID renewal, Qatar labour laws, driving license, and health services.', 
              'ഖത്തർ പ്രവാസികൾക്കായുള്ള മെട്രാഷ്2, വിസ, തൊഴിൽ നിയമം, ഡ്രൈവിംഗ് ലൈസൻസ്, ഹമദ് ഹെൽത്ത് കാർഡ് വിവരങ്ങൾ.');

include __DIR__ . '/includes/header.php';
?>

<main class="container my-4">
    <!-- Hero Header -->
    <div class="p-4 p-md-5 rounded shadow-sm mb-4 text-white" style="background: linear-gradient(135deg, #8A1538 0%, #3e0616 100%);">
        <span class="badge bg-gold text-dark mb-2 text-uppercase fw-bold"><i class="fas fa-passport me-1"></i> <?= t('Official Resident Handbook', 'പ്രവാസി ഹാൻഡ്ബുക്ക്') ?></span>
        <h1 class="display-6 fw-bold mb-2">
            <?= t('Qatar Expat Living & Legal Guide', 'ഖത്തർ പ്രവാസി സമഗ്ര വിവര ഗൈഡ്') ?>
        </h1>
        <p class="lead fs-6 text-white-50 mb-0">
            <?= t('Everything expatriates and newcomers need to know about navigating residence permits, labour rights, health cards, driving licenses, and official government procedures in Doha.',
                  'ഖത്തറിൽ ജോലി ചെയ്യുന്ന പ്രവാസികൾ അറിഞ്ഞിരിക്കേണ്ട വിസ നിയമങ്ങൾ, തൊഴിൽ അവകാശങ്ങൾ, മെട്രാഷ്2 സേവനങ്ങൾ, ഹെൽത്ത് കാർഡ്, ഡ്രൈവിംഗ് ലൈസൻസ് എന്നിവ സംബന്ധിച്ച ആധികാരിക വിവരങ്ങൾ.') ?>
        </p>
    </div>

    <!-- Quick Jump Anchor Bar -->
    <div class="card p-3 shadow-sm border mb-4 bg-light">
        <div class="d-flex flex-wrap gap-2 align-items-center">
            <span class="fw-bold small text-muted me-2"><i class="fas fa-bookmark me-1 text-maroon"></i><?= t('Quick Navigation:', 'പ്രധാന വിഷയങ്ങൾ:') ?></span>
            <a href="#metrash2" class="btn btn-sm btn-outline-maroon"><i class="fas fa-mobile-alt me-1"></i> Metrash2 & QID</a>
            <a href="#labour" class="btn btn-sm btn-outline-maroon"><i class="fas fa-balance-scale me-1"></i> <?= t('Labour Law & Gratuity', 'തൊഴിൽ നിയമം') ?></a>
            <a href="#job-change" class="btn btn-sm btn-outline-maroon"><i class="fas fa-user-tie me-1"></i> <?= t('Changing Jobs', 'തൊഴിൽ മാറ്റം') ?></a>
            <a href="#driving" class="btn btn-sm btn-outline-maroon"><i class="fas fa-id-card me-1"></i> <?= t('Driving License', 'ഡ്രൈവിംഗ് ലൈസൻസ്') ?></a>
            <a href="#health" class="btn btn-sm btn-outline-maroon"><i class="fas fa-hospital me-1"></i> <?= t('Hamad Health Card', 'ഹെൽത്ത് കാർഡ്') ?></a>
            <a href="#contacts" class="btn btn-sm btn-outline-maroon"><i class="fas fa-phone-alt me-1"></i> <?= t('Helplines', 'ഹെൽപ്പ്‌ലൈൻ') ?></a>
        </div>
    </div>

    <div class="row g-4">
        <!-- LEFT: GUIDE CHAPTERS (8 of 12) -->
        <div class="col-lg-8">
            
            <!-- CHAPTER 1: METRASH2 & QID -->
            <section id="metrash2" class="card shadow-sm border mb-4">
                <div class="card-header bg-maroon text-white py-3">
                    <h4 class="mb-0 fw-bold fs-5">
                        <i class="fas fa-mobile-alt me-2 text-warning"></i>
                        1. <?= t('Metrash2 & Qatar ID (QID) Services', 'മെട്രാഷ്2 & ഖത്തർ ഐഡി (QID) സേവനങ്ങൾ') ?>
                    </h4>
                </div>
                <div class="card-body p-4">
                    <p>
                        <?= t('Metrash2 is the official smart services portal developed by the Ministry of Interior (MOI) Qatar. It allows residents, citizens, and company representatives to access over 300 government services directly from their smartphones.',
                              'ഖത്തർ ആഭ്യന്തര മന്ത്രാലയം (MOI) ഒരുക്കിയിരിക്കുന്ന അത്യാധുനിക മൊബൈൽ ആപ്ലിക്കേഷനാണ് മെട്രാഷ്2. മുന്നൂറിലധികം സർക്കാർ സേവനങ്ങൾ ഈ ആപ്പ് വഴി ലഭ്യമാണ്.') ?>
                    </p>
                    
                    <h5 class="text-maroon fw-bold mt-4"><?= t('How to Activate Metrash2:', 'മെട്രാഷ്2 എങ്ങനെ ആക്റ്റിവേറ്റ് ചെയ്യാം:') ?></h5>
                    <ol class="mb-3">
                        <li><?= t('Ensure your mobile SIM card is registered under your own Qatar ID (QID).', 'നിങ്ങളുടെ മൊബൈൽ നമ്പർ നിങ്ങളുടെ സ്വന്തം ഖത്തർ ഐഡിയിൽ എടുത്തതായിരിക്കണം.') ?></li>
                        <li><?= t('Download the Metrash2 app from Google Play Store or Apple App Store.', 'ആപ്പ് സ്റ്റോറിൽ നിന്നോ പ്ലേ സ്റ്റോറിൽ നിന്നോ മെട്രാഷ്2 ആപ്പ് ഡൗൺലോഡ് ചെയ്യുക.') ?></li>
                        <li><?= t('Enter your QID number and QID expiry date.', 'ഖത്തർ ഐഡി നമ്പറും കാലാവധിയും നൽകുക.') ?></li>
                        <li><?= t('Send the verification SMS generated by the app, and set a secure 4-digit PIN code.', 'ആപ്പ് ആവശ്യപ്പെടുന്ന വെരിഫിക്കേഷൻ എസ്.എം.എസ് അയച്ച് 4 അക്ക പിൻ നമ്പർ സെറ്റ് ചെയ്യുക.') ?></li>
                    </ol>

                    <h5 class="text-maroon fw-bold mt-4"><?= t('Key Services Available on Metrash2:', 'മെട്രാഷ്2 വഴിയുള്ള പ്രധാന സേവനങ്ങൾ:') ?></h5>
                    <ul>
                        <li><strong><?= t('Residency Renewal:', 'റെസിഡൻസി പുതുക്കൽ:') ?></strong> <?= t('Renew QID for sponsored family members or company employees with electronic payment and home delivery.', 'കുടുംബാംഗങ്ങളുടെയും കമ്പനി ജീവനക്കാരുടെയും ഐഡി കാർഡുകൾ ഓൺലൈനായി പുതുക്കാം.') ?></li>
                        <li><strong><?= t('Family Visit Visas:', 'ഫാമിലി വിസിറ്റ് വിസ:') ?></strong> <?= t('Apply for 30-day visit visas for spouse, children, and parents with instant paperless document upload.', 'കുടുംബാംഗങ്ങൾക്കായി വിസിറ്റ് വിസ അപേക്ഷ സമർപ്പിക്കാം.') ?></li>
                        <li><strong><?= t('Traffic Services:', 'ട്രാഫിക് സേവനങ്ങൾ:') ?></strong> <?= t('Check traffic violation points, pay traffic fines with 50% discount during amnesty windows, and transfer vehicle ownership.', 'ട്രാഫിക് പിഴകൾ പരിശോധിക്കാനും അടയ്ക്കാനും സാധിക്കും.') ?></li>
                        <li><strong><?= t('Digital Wallet (E-Wallet):', 'ഡിജിറ്റൽ വാലറ്റ്:') ?></strong> <?= t('Carries digital versions of QID, driving license, and vehicle registration (Istimara) legally recognized everywhere in Qatar.', 'ഒറിജിനൽ കാർഡുകൾ കൈവശം ഇല്ലാതെ തന്നെ ഡിജിറ്റൽ കാർഡുകൾ ഉപയോഗിക്കാം.') ?></li>
                    </ul>
                </div>
            </section>

            <!-- CHAPTER 2: LABOUR LAW & GRATUITY -->
            <section id="labour" class="card shadow-sm border mb-4">
                <div class="card-header bg-maroon text-white py-3">
                    <h4 class="mb-0 fw-bold fs-5">
                        <i class="fas fa-balance-scale me-2 text-warning"></i>
                        2. <?= t('Qatar Labour Law, Minimum Wage & End-of-Service Gratuity', 'ഖത്തർ തൊഴിൽ നിയമം, മിനിമം വേതനം & ഗ്രാറ്റുവിറ്റി') ?>
                    </h4>
                </div>
                <div class="card-body p-4">
                    <p>
                        <?= t('Qatar Labour Law No. 14 of 2004, supplemented by historic labour reforms, provides robust legal protections for private-sector employees regardless of nationality.',
                              'ഖത്തർ തൊഴിൽ നിയമം അനുസരിച്ച് സ്വകാര്യ മേഖലയിൽ ജോലി ചെയ്യുന്ന തൊഴിലാളികൾക്ക് കൃത്യമായ അവകാശങ്ങളും ആനുകൂല്യങ്ങളും ഉറപ്പുനൽകുന്നു.') ?>
                    </p>

                    <div class="alert alert-info border-info">
                        <h6 class="fw-bold"><i class="fas fa-coins me-1"></i> <?= t('Statutory Minimum Wage in Qatar:', 'ഖത്തറിലെ നിയമപരമായ മിനിമം വേതനം:') ?></h6>
                        <ul class="mb-0 small">
                            <li><strong><?= t('Basic Minimum Wage:', 'അടിസ്ഥാന ശമ്പളം:') ?></strong> QAR 1,000 <?= t('per month', 'പ്രതിമാസം') ?></li>
                            <li><strong><?= t('Food Allowance:', 'ഭക്ഷണ അലവൻസ്:') ?></strong> QAR 300 <?= t('(if not provided by employer)', '(ഭക്ഷണം നൽകുന്നില്ലെങ്കിൽ)') ?></li>
                            <li><strong><?= t('Accommodation Allowance:', 'താമസ അലവൻസ്:') ?></strong> QAR 500 <?= t('(if accommodation not provided by employer)', '(താമസം നൽകുന്നില്ലെങ്കിൽ)') ?></li>
                            <li><strong><?= t('Total Minimum Package:', 'ആകെ മിനിമം പാക്കേജ്:') ?></strong> <strong>QAR 1,800</strong> <?= t('per month', 'പ്രതിമാസം') ?></li>
                        </ul>
                    </div>

                    <h5 class="text-maroon fw-bold mt-4"><?= t('End-of-Service Gratuity Calculation Formula:', 'സർവീസ് ആനുകൂല്യം (ഗ്രാറ്റുവിറ്റി) കണക്കാക്കുന്ന രീതി:') ?></h5>
                    <p class="small text-muted">
                        <?= t('Applicable upon completing at least one continuous full year of employment:', 'കുറഞ്ഞത് ഒരു വർഷം സർവീസ് പൂർത്തിയാക്കിയവർക്ക്:') ?>
                    </p>
                    <div class="p-3 bg-light rounded border font-monospace text-dark mb-3">
                        <strong>Gratuity Amount</strong> = (Basic Monthly Salary &divide; 30 days) &times; 21 days &times; (Completed Years of Service)
                    </div>
                    <p class="small">
                        <?= t('Note: Fractions of a year are calculated proportionally. Allowances such as housing, transport, phone, or commission are NOT included in the gratuity basic calculation.',
                              'ശ്രദ്ധിക്കുക: ബേസിക് സാലറി (അടിസ്ഥാന ശമ്പളം) മാത്രമാണ് ഗ്രാറ്റുവിറ്റി കണക്കാക്കാൻ ഉപയോഗിക്കുന്നത്. അലവൻസുകൾ ഇതിൽ ഉൾപ്പെടില്ല.') ?>
                    </p>
                </div>
            </section>

            <!-- CHAPTER 3: CHANGING JOBS IN QATAR -->
            <section id="job-change" class="card shadow-sm border mb-4">
                <div class="card-header bg-maroon text-white py-3">
                    <h4 class="mb-0 fw-bold fs-5">
                        <i class="fas fa-user-tie me-2 text-warning"></i>
                        3. <?= t('How to Legally Change Employers (No NOC Required)', 'എൻ.ഒ.സി ഇല്ലാതെ ജോലി മാറുന്ന വിധം') ?>
                    </h4>
                </div>
                <div class="card-body p-4">
                    <p>
                        <?= t('Under Qatar\'s historic reform of the Kafala system, expatriates can transition to a new employer without obtaining a No Objection Certificate (NOC) from their previous sponsor, provided legal notice procedures are strictly respected.',
                              'ഖത്തറിലെ നിയമ പരിഷ്കാരങ്ങൾ പ്രകാരം മുൻ സ്പോൺസറുടെ എൻ.ഒ.സി (NOC) ഇല്ലാതെ തന്നെ തൊഴിലാളികൾക്ക് മറ്റൊരു ജോലിയിലേക്ക് മാറാൻ സാധിക്കും.') ?>
                    </p>

                    <h5 class="text-maroon fw-bold mt-3"><?= t('Mandatory Legal Notice Periods:', 'നോട്ടീസ് പിരീഡ് നിബന്ധനകൾ:') ?></h5>
                    <div class="row g-3 mb-3">
                        <div class="col-md-6">
                            <div class="border rounded p-3 bg-light">
                                <h6 class="fw-bold text-maroon"><?= t('Service Under 2 Years', '2 വർഷത്തിൽ താഴെ സർവീസ്') ?></h6>
                                <p class="small text-muted mb-0">
                                    <?= t('Worker must give at least <strong>1 Month Notice</strong> via the Ministry of Labour online portal.', 
                                          'തൊഴിൽ മന്ത്രാലയത്തിന്റെ ഓൺലൈൻ പോർട്ടൽ വഴി <strong>1 മാസത്തെ നോട്ടീസ്</strong> നൽകണം.') ?>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="border rounded p-3 bg-light">
                                <h6 class="fw-bold text-maroon"><?= t('Service Over 2 Years', '2 വർഷത്തിൽ കൂടുതൽ സർവീസ്') ?></h6>
                                <p class="small text-muted mb-0">
                                    <?= t('Worker must give at least <strong>2 Months Notice</strong> via the Ministry of Labour online portal.', 
                                          'തൊഴിൽ മന്ത്രാലയത്തിന്റെ ഓൺലൈൻ പോർട്ടൽ വഴി <strong>2 മാസത്തെ നോട്ടീസ്</strong> നൽകണം.') ?>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <!-- CHAPTER 4: DRIVING LICENSE -->
            <section id="driving" class="card shadow-sm border mb-4">
                <div class="card-header bg-maroon text-white py-3">
                    <h4 class="mb-0 fw-bold fs-5">
                        <i class="fas fa-car me-2 text-warning"></i>
                        4. <?= t('Getting a Qatar Driving License', 'ഖത്തർ ഡ്രൈവിംഗ് ലൈസൻസ് എടുക്കുന്ന വിധം') ?>
                    </h4>
                </div>
                <div class="card-body p-4">
                    <p>
                        <?= t('Driving in Qatar is strictly regulated by the Traffic Directorate. Expatriate eligibility depends on profession listed on the QID and prior driving experience.',
                              'ഖത്തറിൽ വാഹനം ഓടിക്കാൻ സാധുവായ ഖത്തർ ഡ്രൈവിംഗ് ലൈസൻസ് നിർബന്ധമാണ്.') ?>
                    </p>
                    <div class="row g-3">
                        <div class="col-md-4">
                            <div class="border rounded p-3 bg-light text-center h-100">
                                <i class="fas fa-id-badge fa-2x text-maroon mb-2"></i>
                                <h6 class="fw-bold">GCC License Holders</h6>
                                <p class="small text-muted mb-0"><?= t('Direct conversion or direct road test available depending on nationality and permit validity.', 'നേരിട്ട് ടെസ്റ്റ് നൽകാം.') ?></p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="border rounded p-3 bg-light text-center h-100">
                                <i class="fas fa-clock fa-2x text-maroon mb-2"></i>
                                <h6 class="fw-bold">Half Course (20 Classes)</h6>
                                <p class="small text-muted mb-0"><?= t('Available for holders of recognized home country licenses (e.g. India, Pakistan, Philippines).', 'സ്വന്തം രാജ്യത്തെ ലൈസൻസുള്ളവർക്ക്.') ?></p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="border rounded p-3 bg-light text-center h-100">
                                <i class="fas fa-graduation-cap fa-2x text-maroon mb-2"></i>
                                <h6 class="fw-bold">Full Course (40 Classes)</h6>
                                <p class="small text-muted mb-0"><?= t('Mandatory for new beginners without prior registered driving credentials.', 'പുതുതായി പഠിക്കുന്നവർക്ക് 40 ക്ലാസുകൾ.') ?></p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <!-- CHAPTER 5: HEALTH CARD -->
            <section id="health" class="card shadow-sm border mb-4">
                <div class="card-header bg-maroon text-white py-3">
                    <h4 class="mb-0 fw-bold fs-5">
                        <i class="fas fa-hospital me-2 text-warning"></i>
                        5. <?= t('Hamad Health Card & PHCC Healthcare', 'ഹമദ് ഹെൽത്ത് കാർഡ് & ആരോഗ്യ സേവനങ്ങൾ') ?>
                    </h4>
                </div>
                <div class="card-body p-4">
                    <p>
                        <?= t('The Hamad Health Card entitles holders to heavily subsidized primary and secondary medical care across Hamad Medical Corporation (HMC) hospitals and Primary Health Care Corporation (PHCC) clinics.',
                              'ഹമദ് മെഡിക്കൽ കോർപ്പറേഷന്റെ ആശുപത്രികളിലും ഹെൽത്ത് സെന്ററുകളിലും കുറഞ്ഞ ചെലവിൽ മികച്ച ചികിത്സ ലഭിക്കാൻ ഹെൽത്ത് കാർഡ് സഹായിക്കുന്നു.') ?>
                    </p>
                    <ul class="mb-3">
                        <li><strong><?= t('Annual Adult Fee:', 'മുതിർന്നവർക്കുള്ള വാർഷിക ഫീസ്:') ?></strong> QAR 100</li>
                        <li><strong><?= t('Annual Child Fee (under 18):', 'കുട്ടികൾക്കുള്ള ഫീസ്:') ?></strong> QAR 50</li>
                        <li><strong><?= t('Consultation Co-Pay:', 'കൺസൾട്ടേഷൻ ഫീസ്:') ?></strong> <?= t('Subsidized consultations from QAR 10 - QAR 20 with prescriptions at nominal cost.', '10 മുതൽ 20 റിയാൽ വരെ മാത്രം.') ?></li>
                    </ul>
                </div>
            </section>
        </div>

        <!-- RIGHT: SIDEBAR (4 of 12) -->
        <div class="col-lg-4">
            <aside class="sidebar">
                <?php render_emergency_widget($settings); ?>
                <?php render_facebook_box($settings); ?>
                <?php render_currency_widget($settings); ?>
            </aside>
        </div>
    </div>
</main>

<?php include __DIR__ . '/includes/footer.php'; ?>
